name: PR Review

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Type check
      run: npx tsc --noEmit
      
    - name: Build project
      run: npm run build
      
    - name: Cache build output
      uses: actions/cache@v3
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

  image-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Check image sizes
      run: |
        echo "Checking image sizes..."
        find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" \) -exec ls -lh {} \; | awk '{if($5>1000000) print $9, $5}'
      
    - name: Install image optimization tools
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
        
    - name: Check image dimensions
      run: |
        echo "Checking image dimensions..."
        find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" -o -iname "*.webp" \) -exec identify -format '%f: %wx%h\n' {} \; | awk -F'[x:]' '{if($2>4000 || $3>4000) print $1, $2"x"$3}'
        
    - name: Check WebP conversion possibility
      run: |
        echo "Checking images that could be converted to WebP..."
        find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -print
        
    - name: Validate image metadata
      run: |
        echo "Checking image metadata..."
        find . -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -exec identify -verbose {} \; | grep -E 'Image:|Filesize:|Resolution:|Compression:|Format:'
